#Installing Centos Default Packeges
#Developers Arman Baghajyan Gurgen Martirosyan
#Changes: Arman Baghajyan, Adding Nginx service check and restart
#Date: 06/06/2018
#Version: 1.1.0

- hosts: hostname
  tasks:
  - name: Creationg nginx main config file
    template:
       src: /root/ansible/templates/nginx/nginx.conf.j2
       dest: '/etc/nginx/nginx.conf'
  - name: Make changis in nginx.conf file
    blockinfile:
      path: /etc/nginx/nginx.conf
      insertafter: "##########################################################"
      content: |
         include /etc/nginx/conf.d/{{ item }}/*.conf;
      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
    with_items:
      - domain name
    
- import_playbook: checknginx_conf.yml
